export const MOCK_CLIENTS = {
  totalRecords: 30,
  Clients: [
    {
      _id: "1",
      clientName: "Acme Corporation",
      industry: "Technology",
      phoneNo: "+1 (555) 123-4567",
      email: "contact@acmecorp.com",
      countryCode: "US",
    },
    {
      _id: "2",
      clientName: "TechStart Solutions",
      industry: "Software Development",
      phoneNo: "+44 20 7946 0958",
      email: "info@techstart.co.uk",
      countryCode: "GB",
    },
    {
      _id: "3",
      clientName: "Global Manufacturing Ltd",
      industry: "Manufacturing",
      phoneNo: "+49 30 12345678",
      email: "contact@globalmanuf.de",
      countryCode: "DE",
    },
    {
      _id: "4",
      clientName: "Innovate Systems",
      industry: "IT Services",
      phoneNo: "+1 (555) 234-5678",
      email: "support@innovatesys.com",
      countryCode: "US",
    },
    {
      _id: "5",
      clientName: "Pacific Trading Co",
      industry: "Retail",
      phoneNo: "+81 3-1234-5678",
      email: "sales@pacifictrade.jp",
      countryCode: "JP",
    },
    {
      _id: "6",
      clientName: "Digital Ventures Inc",
      industry: "Digital Marketing",
      phoneNo: "+1 (555) 345-6789",
      email: "hello@digitalventures.com",
      countryCode: "US",
    },
    {
      _id: "7",
      clientName: "Summit Enterprises",
      industry: "Consulting",
      phoneNo: "+61 2 9876 5432",
      email: "contact@summit.com.au",
      countryCode: "AU",
    },
    {
      _id: "8",
      clientName: "Quantum Technologies",
      industry: "Research & Development",
      phoneNo: "+1 (555) 456-7890",
      email: "info@quantumtech.com",
      countryCode: "US",
    },
    {
      _id: "9",
      clientName: "NextGen Industries",
      industry: "Automotive",
      phoneNo: "+33 1 42 86 82 00",
      email: "contact@nextgen.fr",
      countryCode: "FR",
    },
    {
      _id: "10",
      clientName: "Enterprise Partners LLC",
      industry: "Financial Services",
      phoneNo: "+1 (555) 567-8901",
      email: "partners@enterprise.com",
      countryCode: "US",
    },
    {
      _id: "11",
      clientName: "Blue Ocean Logistics",
      industry: "Logistics",
      phoneNo: "+65 6123 4567",
      email: "operations@blueocean.sg",
      countryCode: "SG",
    },
    {
      _id: "12",
      clientName: "Green Energy Corp",
      industry: "Energy",
      phoneNo: "+47 22 12 34 56",
      email: "info@greenenergy.no",
      countryCode: "NO",
    },
    {
      _id: "13",
      clientName: "Alpha Healthcare",
      industry: "Healthcare",
      phoneNo: "+1 (555) 678-9012",
      email: "admin@alphahealthcare.com",
      countryCode: "US",
    },
    {
      _id: "14",
      clientName: "Silverline Consulting",
      industry: "Business Consulting",
      phoneNo: "+91 11 2345 6789",
      email: "contact@silverline.in",
      countryCode: "IN",
    },
    {
      _id: "15",
      clientName: "Metro Construction Ltd",
      industry: "Construction",
      phoneNo: "+971 4 123 4567",
      email: "projects@metroconstruct.ae",
      countryCode: "AE",
    },
  ],
};

export const INDUSTRY_OPTIONS = [
  { label: "Technology", value: "Technology" },
  { label: "Software Development", value: "Software Development" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "IT Services", value: "IT Services" },
  { label: "Retail", value: "Retail" },
  { label: "Digital Marketing", value: "Digital Marketing" },
  { label: "Consulting", value: "Consulting" },
  { label: "Research & Development", value: "Research & Development" },
  { label: "Automotive", value: "Automotive" },
  { label: "Financial Services", value: "Financial Services" },
  { label: "Logistics", value: "Logistics" },
  { label: "Energy", value: "Energy" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Business Consulting", value: "Business Consulting" },
  { label: "Construction", value: "Construction" },
];

export const COUNTRY_OPTIONS = [
  { label: "United States", value: "US" },
  { label: "United Kingdom", value: "GB" },
  { label: "Germany", value: "DE" },
  { label: "Japan", value: "JP" },
  { label: "Australia", value: "AU" },
  { label: "France", value: "FR" },
  { label: "Singapore", value: "SG" },
  { label: "Norway", value: "NO" },
  { label: "India", value: "IN" },
  { label: "United Arab Emirates", value: "AE" },
];
