import { FileText, FileSpreadsheet, Printer } from "lucide-react";
import Button from "@/components/ui/button/Button";

export default function FooterSection() {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 flex flex-col sm:flex-row justify-between items-center gap-4 transition-colors">
      <div>
        <p className="text-gray-600 dark:text-gray-300 text-sm">
          Last updated:{" "}
          <span
            id="currentTime"
            className="font-semibold text-gray-700 dark:text-gray-200"
          ></span>
        </p>
        <p className="text-gray-500 dark:text-gray-400 text-xs mt-1">
          Generated by Task Management System
        </p>
      </div>
      <div className="flex gap-3 flex-wrap">
        <Button className="flex items-center" variant="outline">
          <FileText className="w-4 h-4" />
          Export PDF
        </Button>
        <Button variant="primary">
          <FileSpreadsheet className="w-4 h-4" />
          Export Excel
        </Button>
        <Button
          onClick={() => {
            window.print();
          }}
        >
          <Printer className="w-4 h-4" />
          Print Dashboard
        </Button>
      </div>
    </div>
  );
}